package com.flash.light.service

object ServiceAction {
    const val ACTION_START_AUDIO_CLASSIFIER = "ACTION_START_AUDIO_CLASSIFIER"
    const val ACTION_STOP_AUDIO_CLASSIFIER = "ACTION_STOP_AUDIO_CLASSIFIER"
    const val ACTION_STOP_ALERT = "ACTION_STOP_ALERT"
}