package com.flash.light.utils

object Constant {
    const val KEY_SP_CURRENT_SOUND_MODEL = "KEY_SP_CURRENT_SOUND_MODEL"
    const val KEY_SP_CURRENT_DURATION = "KEY_SP_CURRENT_DURATION"
    const val KEY_SP_CURRENT_FLASH= "KEY_SP_CURRENT_FLASH"
    const val KEY_SP_CURRENT_FLASH_MODE= "KEY_SP_CURRENT_FLASH_MODE"
    const val KEY_SP_CURRENT_VIBRATION = "KEY_SP_CURRENT_VIBRATION"
    const val KEY_SP_CURRENT_VIBRATION_MODE = "KEY_SP_CURRENT_VIBRATION_MODE"
    const val KEY_SP_CURRENT_VOLUME = "KEY_SP_CURRENT_VOLUME"
    const val KEY_SP_CURRENT_ENABLE_VOLUME = "KEY_SP_CURRENT_ENABLE_VOLUME"
    const val KEY_SP_CURRENT_SENSITIVITY = "KEY_SP_CURRENT_SENSITIVITY"
    const val KEY_SP_CURRENT_LANGUAGE = "KEY_SP_CURRENT_LANGUAGE"
    const val KEY_SP_CURRENT_WAKEUP = "KEY_SP_CURRENT_WAKEUP"
    const val KEY_SP_SHOW_ONBOARDING = "KEY_SP_SHOW_ONBOARDING"
    const val KEY_SP_RUNNING_AUDIO_CLASSIFIER = "KEY_SP_RUNNING_AUDIO_CLASSIFIER"
    const val KEY_REVIEW_APP = "key_review_app"
    const val KEY_SP_UMP_SHOWED = "KEY_SP_UMP_SHOWED"
    const val KEY_SP_UMP_SETTING_SHOWED = "KEY_SP_UMP_SETTING_SHOWED"
}